examples/pipelines/finetune_stable_diffusion/components.config, examples/pipelines/finetune_stable_diffusion/config/general_config.py, examples/pipelines/finetune_stable_diffusion/project.config, examples/pipelines/finetune_stable_diffusion/start_cluster.sh, examples/pipelines/finetune_stable_diffusion/stop_cluster.sh
Update configs (artifact registry, kfp host path, project name) necessary for uploading kfp pipelines
=> modify kfp configs to new project

fondant/component_spec.py, fondant/schemas/component_spec.json, tests/example_specs/evolution_examples/8/component.yaml, tests/example_specs/evolution_examples/8/output_manifest.json
=> Make input and output subsets in component spec optional

examples/pipelines/simple_pipeline/components/image_filtering/requirements.txt, examples/pipelines/simple_pipeline/components/image_filtering/src/fondant_component.yaml, examples/pipelines/simple_pipeline/components/load_from_hub/kubeflow_component.yaml, examples/pipelines/simple_pipeline/components/load_from_hub/requirements.txt, examples/pipelines/simple_pipeline/components/load_from_hub/src/fondant_component.yaml, examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py, examples/pipelines/simple_pipeline/simple_pipeline.py, fondant/dataset.py, fondant/pipeline_utils.py
This PR uses the new `hf://` fsspec specification to read a Dask dataframe directly from the hub.
=> Use hf filesystem for loading component

.pre-commit-config.yaml, examples/pipelines/config.py, examples/pipelines/finetune_stable_diffusion/components/clip_downloader_component/src/main.py, examples/pipelines/finetune_stable_diffusion/components/clip_downloader_component/src/utils/image_downloader.py, examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/main.py, examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/utils/embedding_utils.py, examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/utils/knn_service.py, examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/utils/timer.py, examples/pipelines/finetune_stable_diffusion/components/image_caption_component/src/main.py, examples/pipelines/finetune_stable_diffusion/components/image_caption_component/src/utils/blip_model.py, examples/pipelines/finetune_stable_diffusion/components/image_caption_component/src/utils/image_captioning.py, examples/pipelines/finetune_stable_diffusion/components/image_conversion_component/src/main.py, examples/pipelines/finetune_stable_diffusion/components/image_conversion_component/src/utils/img_conversion.py, examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/main.py, examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/train_text_to_image.py, examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/utils/dataset_utils.py, examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/utils/training_utils.py, examples/pipelines/finetune_stable_diffusion/config/general_config.py, examples/pipelines/finetune_stable_diffusion/sd_finetuning_pipeline.py, examples/pipelines/simple_pipeline/components/image_filtering/src/main.py, examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py, examples/pipelines/simple_pipeline/config/general_config.py, examples/pipelines/simple_pipeline/simple_pipeline.py, tests/test_component.py, tests/test_component_specs.py, tests/test_dataset.py, tests/test_import_utils.py, tests/test_logger.py, tests/test_manifest.py, tests/test_manifest_evolution.py
I will do the same for Ruff as well as a next step.
=> Run black on tests and all examples

examples/pipelines/simple_pipeline/components/image_filtering/src/main.py, examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
Small follow-up to #74 to update the simple pipeline components.
=> Update simple pipeline components to use new interface

tests/test_manifest.py
Pipeline on main was failing after merging #80 en #83 separately.
=> Run ruff on new manifest tests

fondant/schemas/component_spec.json
This PR adds some small improvements to the component schema:
- Make args optional in component spec
- Add minProperties:1 to subsets in component 
- Add default to additionalSubsets and additionalFields in component schema
=> Component schema improvements

examples/pipelines/pipeline_configs.py
Small PR to update the default base path of kfp to the current relevant one
=> update default kfp base path

docs/component_spec.md, mkdocs.yml
Fixes #64 
Click the `Details` button next to the documentation build step to see the generated docs.
=> Add component spec documentation

docs/component_spec.md, docs/custom_component.md, docs/manifest.md, mkdocs.yml
=> Add custom component docs

fondant/component.py
Small bug introduced by refactoring after testing #226
=> Reassign dataframe after dropping extra columns

.github/workflows/build.yaml, scripts/build_components.sh
The array of images was not reset in between loops, leading to the same image being set in each component specification.
=> Redefine empty images array each loop

fondant/component_spec.py, fondant/manifest.py, pyproject.toml
This PR fixes some deprecation warnings which show up in the tests. There's still a bunch of warnings remaining, but I think they're all coming from KfP.
=> Fix test warnings

src/fondant/data_io.py
Fixes issues when merging dataframes with different number of partitions
=> Change subset merging method

examples/pipelines/commoncrawl/components/download_commoncrawl_segments/fondant_component.yaml, examples/pipelines/commoncrawl/components/download_commoncrawl_segments/requirements.txt, examples/pipelines/commoncrawl/components/download_commoncrawl_segments/src/main.py, examples/pipelines/commoncrawl/components/download_commoncrawl_segments/src/utils/download_utils.py, examples/pipelines/commoncrawl/components/download_commoncrawl_segments/src/utils/text_utils.py
- Add trafilatura to enable a enhanced html extraction
- Initialise boto3 session once
=> [CommonCrawl pipeline] Improve html extraction

components/load_from_files/README.md, docs/pipeline.md, examples/pipelines/controlnet-interior-design/pipeline.py, src/fondant/component_spec.py, src/fondant/data_io.py, src/fondant/executor.py, src/fondant/pipeline.py, tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml, tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml, tests/example_pipelines/compiled_pipeline/example_2/docker-compose.yml, tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml, tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml, tests/example_specs/component_specs/kubeflow_component.yaml, tests/test_compiler.py, tests/test_component.py, tests/test_data_io.py, tests/test_pipeline.py
PR to remove automatic logic of repartitioning the output based on size
=> Remove output_partition_size argument and logic

examples/pipelines/commoncrawl/components/download_commoncrawl_segments/fondant_component.yaml
=> [Commoncrawl pipeline] Add metadata for target_language

examples/pipelines/commoncrawl/components/load_from_commoncrawl/fondant_component.yaml, examples/pipelines/commoncrawl/components/load_from_commoncrawl/src/main.py
This PR allows selecting segments by offsets. This is useful if we cannot run all segments at a go.
=> [Commoncrawl pipeline] Add offset to load component

src/fondant/data_io.py
Apparently we are currently not preserving the divisions of the data when writing and reading to parquet. We are preserving the partitions when reading initially, but since divisions are no longer known, the partitions will be shuffled when we merge the index and subsets together.
Let's create a dataframe with known partitions and write it to parquet:
```python
ddf = dd.from_dict({"data": list(range(5))}, npartitions=5)
ddf.known_divisions
Out: True
ddf.divisions
Out: (0, 1, 2, 3, 4, 4)
ddf.to_parquet("/tmp/data")
```
If we read it back, we see that the partitions are preserved, but the division information is not.
```python
index_df = dd.read_parquet("/tmp/data")
index_df = index_df.drop("data", axis=1)
index_df.map_partitions(len).compute()
Out: 
0    1
1    1
2    1
3    1
4    1 …
```
=> Preserve divisions when writing and reading

README.md
Convert readme to html to display the list correctly.
=> Convert readme to html

pyproject.toml
This will update the PyPI description on the next release.
=> Update project description

docs/announcements/CC_25M_community.md
Add dataset link to press release.
=> Add dataset link to press release

components/caption_images/README.md, components/download_images/README.md, components/embed_images/README.md, components/embedding_based_laion_retrieval/README.md, components/filter_comments/README.md, components/filter_image_resolution/README.md, components/filter_line_length/README.md, components/image_cropping/README.md, components/image_resolution_extraction/README.md, components/language_filter/README.md, components/load_from_files/README.md, components/load_from_hf_hub/README.md, components/load_from_parquet/README.md, components/minhash_generator/README.md, components/pii_redaction/README.md, components/prompt_based_laion_retrieval/README.md, components/segment_images/README.md, components/text_length_filter/README.md, components/text_normalization/README.md, components/write_to_hf_hub/README.md, docs/.readthedocs.yaml, docs/components/components.md, docs/components/hub.md, docs/overrides/partials/toc.html, mkdocs.yml, scripts/component_readme/generate_hub.py, scripts/component_readme/hub_template.md, scripts/component_readme/readme_template.md
This PR adds a script and template to automatically add a component hub page to our docs.
=> Add component hub doc page

.pre-commit-config.yaml, components/embedding_based_laion_retrieval/src/clip_client.py, components/pii_redaction/src/pii_redaction.py, components/prompt_based_laion_retrieval/src/clip_client.py, pyproject.toml
Let's run bandit on the components as well.
=> Run bandit on components

docs/components/custom_component.md
Update component docs to make it more explicit where resources and models should be defined.
=> Update component docs

docs/components/custom_component.md, tests/example_component/Dockerfile, tests/example_component/fondant_component.yaml, tests/test_cli.py
This PR adds documentation and a test case for the fondant build command. 
fix #530
=> Fondant build - add test case and documentation

mkdocs.yml
=> Add search bar to the documentation

pyproject.toml
Fix issue with writing small partition sizes
=> Bump gcsfs

README.md
PR removes the reference to the star coder pipeline from readme
=> Remove starcoder pipeline reference from README.md

components/caption_images/Dockerfile, components/chunk_text/Dockerfile, components/download_images/Dockerfile, components/embed_images/Dockerfile, components/embed_text/Dockerfile, components/embedding_based_laion_retrieval/Dockerfile, components/filter_image_resolution/Dockerfile, components/image_cropping/Dockerfile, components/image_resolution_extraction/Dockerfile, components/index_weaviate/Dockerfile, components/language_filter/Dockerfile, components/language_filter/tests/language_filter_component_test.py, components/load_from_files/Dockerfile, components/load_from_hf_hub/Dockerfile, components/load_from_hf_hub/src/main.py, components/load_from_parquet/Dockerfile, components/load_from_parquet/src/main.py, components/minhash_generator/Dockerfile, components/minhash_generator/tests/component_test.py, components/prompt_based_laion_retrieval/Dockerfile, components/resize_images/Dockerfile, components/segment_images/Dockerfile, components/text_length_filter/Dockerfile, components/text_length_filter/tests/text_length_filter_test.py, components/text_normalization/Dockerfile, components/write_to_hf_hub/Dockerfile, components/write_to_hf_hub/src/main.py, pyproject.toml, src/fondant/component/__init__.py
=> Add component install extra and update others

.pre-commit-config.yaml, pyproject.toml
The pre-commit was failing due to missing dependencies.
=> Fixing pre-commit building component READMEs

src/fondant/core/component_spec.py, src/fondant/core/manifest.py, src/fondant/pipeline/pipeline.py, src/fondant/testing.py, tests/test_compiler.py, tests/test_pipeline.py
Bugfix that fixes the component name based on the expected format in different places (kfp, component folder, original name, ...)
=> Fix naming error

components/chunk_text/requirements.txt, components/embed_text/requirements.txt, tests/sample_pipeline_test/components/dummy_component/requirements.txt
Increase langchain version to avoid "Langchain Server-Side Request Forgery vulnerability"
=> Update langchain version

docs/components/publishing_components.md
There was already documentation provided here, added a small section for the local runner
=> publishing Components

scripts/component_readme/generate_hub.py, scripts/component_readme/hub_template.md
=> Use names instead of directory names in hub

components/index_qdrant/README.md, components/index_qdrant/fondant_component.yaml
This should fix the pipeline on main. I forgot to include this change since pre-commit was broken as long as the component spec changes were not merged to main.
=> Regenerate qdrant readme

components/chunk_text/fondant_component.yaml, components/chunk_text/src/main.py, src/fondant/cli.py
Also contains a fix to the explorer command.
=> Fix column names in chunk_text component

components/caption_images/README.md, components/chunk_text/README.md, components/crop_images/README.md, components/download_images/README.md, components/embed_images/README.md, components/embed_text/README.md, components/extract_image_resolution/README.md, components/filter_image_resolution/README.md, components/filter_language/README.md, components/filter_text_length/README.md, components/generate_minhash/README.md, components/index_qdrant/README.md, components/index_weaviate/README.md, components/load_from_files/README.md, components/load_from_hf_hub/README.md, components/load_from_parquet/README.md, components/normalize_text/README.md, components/resize_images/README.md, components/retrieve_laion_by_embedding/README.md, components/retrieve_laion_by_prompt/README.md, components/segment_images/README.md, components/write_to_hf_hub/README.md, scripts/component_readme/generate_readme.py, scripts/component_readme/readme_template.md
This PR updates the component generation to take into account the component type and generate the appropriate usage example.
=> Update component README generation for new pipeline interface

src/fondant/pipeline/compiler.py
Add branches to make sure we only pullthrough and patch reusable components.
=> Add logic to handle custom components

src/fondant/pipeline/compiler.py, tests/pipeline/test_compiler.py
More of a bandaid, I need to refactor this to make it more robust.
=> Remove single quotes

components/embed_text/README.md, components/embed_text/fondant_component.yaml, components/embed_text/src/main.py, components/embed_text/tests/embed_text_test.py
Reduce from infinite retires to a fix number
=> Fix retry mechanism embedding component 

components/chunk_text/README.md, components/chunk_text/fondant_component.yaml, components/chunk_text/src/main.py, components/chunk_text/tests/chunk_text_test.py, components/index_aws_opensearch/README.md
Fixes [#14](https://github.com/ml6team/fondant-usecase-RAG/issues/14)
Adds different chunking strategies that are available in langchain. 
Affected pipelines must be updated after a new release
=> Generalize chunk data component

src/fondant/component/executor.py, src/fondant/core/component_spec.py
Needed some refactoring while working on #751.
Submitting this as a separate PR for easy reviewing.
=> Accept actual type instead of string representation in Argument class

docs/guides/installation.md, src/fondant/pipeline/runner.py, tests/integration_tests/test_sample_pipeline.py, tests/pipeline/test_runner.py, tests/test_cli.py
Temp fix for https://github.com/ml6team/fondant/issues/344 until we can build reasonably sized ARM images.
=> Add env var to force amd platform on docker runner

scripts/component_readme/readme_template.md
Fixes readme generation which was broken by #761.
Due to the setup of the pre-commit hook, this was only detected after merging to main.
=> Fix readme generation

.github/workflows/pipeline.yaml, pyproject.toml
Let me know if missed something somewhere
=> Bump kfp version and enable python 3.11

docs/components/components.md, docs/components/custom_containerized_component.md, docs/components/custom_python_component.md, docs/documentation_guide.md, docs/guides/build_a_simple_pipeline.md, docs/guides/implement_custom_components.md, mkdocs.yml
Fixes https://github.com/ml6team/fondant/issues/809
Fixes https://github.com/ml6team/fondant/issues/810
=> Add initial docs on Python Components

.github/workflows/build.yaml, scripts/build_base_image.sh
Change dev image build step. Build and tag image with additional `dev` tag.
=> Enable build of fondant dev base image

src/fondant/explore.py, tests/test_explorer.py
Adding docker default platform to the execution command of the data explorer.
=> Add docker default platform to data explorer

components/index_weaviate/README.md, components/index_weaviate/fondant_component.yaml
Small changes to the index weaviate component readme.
=> Update readme index weaviate component

src/fondant/pipeline/runner.py, tests/pipeline/test_runner.py
Common and not obvious issue with users is outdated docker versions
=> Validate docker versions

docs/.readthedocs.yaml
https://github.com/readthedocs/readthedocs.org/issues/11150
https://github.com/python-poetry/poetry/issues/9025
=> Fix docs build for Poetry >=1.8

src/fondant/components/load_from_hf_hub/Dockerfile
Seems like this was accidentally committed.
=> Update Fondant version in load_from_hub component

src/fondant/core/component_spec.py, src/fondant/core/schemas/component_spec.json, tests/pipeline/test_lightweight_component.py
PR that enables defining default values for lightweight components
=> Fix default lightweight component

docs/components/lightweight_components.md
Small update the documentation based on discord feedback.
=> Update documentation lightweight_components

README.md
Fixes: https://github.com/ml6team/fondant/issues/932
=> Fix arch link in readme
