ml6team/fondant

.pre-commit-config.yaml
express/gcp_storage.py
pyproject.toml

Final check to migrate from the Bitbucket pipelines.

Add bandit to pre-commit

---

.pre-commit-config.yaml
express/components/common.py
express/components/pandas_components.py
express/gcp_storage.py
express/logger.py
express/manifest.py
express/storage_interface.py

From the black website:
> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
> 
> Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.
> 
> Black makes code review faster by producing the smallest diffs possible.
We've been using it on Connexion for about a year and it's a pleasure to work with once its usage is automated by pre-commit.

Add black formatting

---

.github/workflows/pipeline.yaml
.pre-commit-config.yaml
express/components/__init__.py
express/components/common.py
express/components/pandas_components.py
express/manifest.py
express/storage_interface.py
pyproject.toml

Based on [Niels' suggestion](https://github.com/ml6team/express/pull/11#issuecomment-1461521485).
Ruff is a lot faster than Pylint and an also prevents the need for isort. While it [doesn't completely cover all pylint checks](https://github.com/charliermarsh/ruff/issues/970), a lot of the non-covered issues will be covered by bandit or mypy (still to add) instead.

Switch pylint for Ruff

---

examples/components/single_node/README.md
examples/components/single_node/data_loading_hf_datasets.py
examples/components/single_node/data_loading_pandas.py
express/components/hf_datasets_components.py
express/manifest.py
license_strategy.ini
pyproject.toml

This PR adds boilerplate `HFDatasetLoaderComponent` and `HFDatasetTransformComponent` classes.
Questions:
- in the Datasets library, there's a distinction between a `Dataset` and a `DatasetDict`. The latter is just a dictionary of several `Dataset` instances, with keys like "train", "validation", "test". I assume the index could be stored as a `Dataset`, whereas data sources can be either a `Dataset` or a `DatasetDict`.
- if you use [`load_dataset`](https://huggingface.co/docs/datasets/v2.10.0/en/package_reference/loading_methods#datasets.load_dataset) without providing a split (like "train", "validation"), this method returns a `DatasetDict` instead of a `Dataset`. So was wondering how we could handle these splits a user might have.
To do:

Add HF Dataset components

---

express/exceptions.py
express/manifest.py
express/schemas/manifest.json
pyproject.toml
tests/test_manifest.py

This PR updates the manifest class to match the discussion on the dataset doc. Let's focus all further discussion on the manifest in this PR.
- I included a schema defining the manifest
- Data sources has been renamed to subsets
- The manifest now defines which fields / columns are available in a subset and their types
- The location for each subset is resolved with the base path defined in the metadata
- I'm no longer leveraging `dataclasses-json` as I don't just want to build a 1 to 1 mapping of the json in Python
- All unused keys have been removed from the manifest
The `Manifest` class is currently mostly focused on making an existing json manifest easily accessible, which is useful for input manifests. We might want to add functionality to create a new manifest programmatically as …

Update manifest class to match discussed specification

---

.github/workflows/pipeline.yaml
express/io.py
tests/test_components_specs.py

This PR adds pytest to the Github actions, to make sure tests are run each time a PR is made.

Add pytest to Github actions

---

express/component_spec.py

PR that adds the input and output arguments of the component as a property to the `ExpressComponent` class for ease of retrieval

Add input and output arguments as ComponentSpec properties 

---

fondant/component_spec.py
fondant/dataset.py
tests/component_example/valid_component/kubeflow_component.yaml
tests/test_components_specs.py

This PR extracts all the kubeflow logic from the `ComponentSpec` to the `KubeflowComponent` so the `ComponentSpec` is a minimal representation of the fondant component specification. I also brought the classes a bit more in line with the `Manifest` class.
This is preparation for the work to deduct the output manifest from the input manifest and component spec only.

Extract kubeflow logic from ComponentSpec to KubeflowComponent

---

fondant/schemas/common.json
fondant/schemas/component_spec.json
fondant/schemas/manifest.json

This PR:
- shares the `field` and `fields` definitions between the manifest and component spec
- Moves object definitions into the `definitions` block for the component spec
- Formats the schema files

Align manifest and component spec schemas

---

examples/pipelines/simple_pipeline/components/image_filtering/requirements.txt
examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
examples/pipelines/simple_pipeline/components/load_from_hub/requirements.txt
examples/pipelines/simple_pipeline/config/general_config.py
examples/pipelines/simple_pipeline/simple_pipeline.py
fondant/dataset.py
fondant/pipeline_utils.py

This PR removes the need for a specific prefix, as we can just include that in the base path of the configuration.

Remove cloud specific prefix

---

fondant/pipeline_utils.py

Kubeflow requires unique pipeline names when uploading pipeline. 
Previous implementations relied on deleting the pipeline using the sdk by finding if it exits using either the `client.list_pipelines()` and filtering on the pipeline name or the `client.get_pipeline_id(pipeline_name)` and then finding existing versions from the the id, deleting them before deleting the pipeline. 
Recent issues started appearing when pipelines were compiled with the v2 SDK. Both functions mentioned above stopped working. Error message: 
`Failed to list pipelines with context \u0026{0xc0001ee9a0}, options \u0026{100 0xc0012d1880}: InternalServerError: Failed to execute SQL for listing pipelines: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version …

add hotfix for uploading kubeflow pipelines

---

fondant/component_spec.py
fondant/manifest.py
fondant/schemas/component_spec.json
tests/example_specs/evolution_examples/1/component.yaml
tests/example_specs/evolution_examples/1/output_manifest.json
tests/example_specs/evolution_examples/2/component.yaml
tests/example_specs/evolution_examples/2/output_manifest.json
tests/example_specs/evolution_examples/3/component.yaml
tests/example_specs/evolution_examples/3/output_manifest.json
tests/example_specs/evolution_examples/4/component.yaml
tests/example_specs/evolution_examples/4/output_manifest.json
tests/example_specs/evolution_examples/5/component.yaml
tests/example_specs/evolution_examples/5/output_manifest.json
tests/example_specs/evolution_examples/6/component.yaml
tests/example_specs/evolution_examples/6/output_manifest.json
tests/example_specs/evolution_examples/7/component.yaml
tests/example_specs/evolution_examples/7/output_manifest.json
tests/example_specs/evolution_examples/input_manifest.json
tests/test_components_specs.py
tests/test_manifest_evolution.py

Don't be alarmed by the size of this PR, it contains a lot of test cases :sweat_smile: 
This PR adds functionality to generate the output manifest based on the input manifest and component specification alone. By deducting the output manifest this way, it can be used for validation of the output data in the component, and for static validation of the pipeline before execution.
I implemented this as an `.evolve()` method on the manifest, since the input manifest is always the starting point. This will also allow for nice chaining in the future. The method is quite long, but I don't think splitting it up will improve readability.
This PR only provides the functionality and tests. As a next step, we'll have to integrate this into the `Dataset` class to actually leverage the functionality for …

Evolve manifest based on component spec

---

.github/workflows/pipeline.yaml
pyproject.toml

Fixes #47 
Coverage allows you to set a threshold for accepted coverage decline. Above it, the pipeline will fail. I currently set it at 0% since we should increase our coverage.

Add coverage check

---

.pre-commit-config.yaml
examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
examples/pipelines/simple_pipeline/config/general_config.py
examples/pipelines/simple_pipeline/simple_pipeline.py
fondant/component.py
fondant/component_spec.py
fondant/dataset.py
fondant/import_utils.py
fondant/logger.py
fondant/manifest.py
fondant/pipeline_utils.py
fondant/schema.py
pyproject.toml
tests/example_data/raw/split.py
tests/test_component.py
tests/test_component_specs.py
tests/test_dataset.py
tests/test_import_utils.py
tests/test_logger.py
tests/test_manifest.py
tests/test_manifest_evolution.py

This PR makes Ruff run on tests as well and adds extra rules:
- More Pylint rules not yet covered by default checks
- Isort for import order
- Pydocstyle rules
- I ignored quite a few rules here, which we might want to activate (D100 - D107), but we can do that in separate PRs as they require manual effort.
I only had to fix one issue and add one local ignore. All other issues were auto-fixed, so these rules shouldn't lead to additional overhead.

Extend Ruff to tests and with extra rules

---

pyproject.toml

I would have expected poetry to convert the caret requirements into something generic that other tools such as `pip` could handle as well, but apparently this is not the case.
Best practice for frameworks / libraries is also to not pin any upper limits unless there are clear incompatibilities, so I switched all the caret versioning to `>=`.
[Relevant discussion on the Poetry repo](https://github.com/orgs/python-poetry/discussions/3757#discussioncomment-435337).

Move from caret to inequality requirements

---

docs/manifest.md
mkdocs.yml

Fixes #62
Please check if there's anything I forgot to explain :)

Add manifest documentation

---

fondant/component_spec.py
tests/example_specs/component_specs/valid_component_no_args.yaml
tests/test_component_specs.py

Follow-up of #87 which tests whether a component spec without any args is supported.

Add test for component spec without args

---

.github/workflows/release.yaml

Fixes #112 
Adapted from the [connexion pipeline](https://github.com/spec-first/connexion/blob/main/.github/workflows/release.yml) to leverage "trusted publishing" using OpenID connect.
We leverage the reusable [gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) action.
I don't think there's away around merging this to test it.

Add workflow to publish package to PyPI

---

.github/workflows/release.yaml
scripts/build_components.sh
scripts/pre-build.sh

Fixes for the release pipeline:
- `GITHUB_REF` contains the full ref in the format `refs/tags/<tag>`, while `GITHUB_REF_NAME` only contains `<tag>`
- `set -e` in bash scripts to make the pipeline fail if the scripts fail.
- Fix paths in `pre-build.sh` script

Bugfix for release pipeline

---

components/prompt_based_laion_retrieval/src/main.py
examples/pipelines/controlnet-interior-design/components/generate_prompts/src/main.py
examples/pipelines/controlnet-interior-design/pipeline.py
examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
examples/pipelines/simple_pipeline/pipeline.py
fondant/component.py
fondant/component_spec.py
fondant/data_io.py
fondant/manifest.py
fondant/pipeline.py
tests/test_component.py
tests/test_component_specs.py
tests/test_data_io.py
tests/test_manifest_evolution.py
tests/test_pipeline.py

Remove Fondant- prefix from class names

---

examples/pipelines/controlnet-interior-design/components/prompt_based_laion_retrieval

This PR adds a temporary symlink from the ControlNet example pipeline to the `prompt_based_laion_retrieval` component to be able to develop the example pipeline more easily while we develop Fondant. We can now just work as if the component was still located in the example directory.
The symlink should be removed before alpha release.

Add symlink to prompt_based_laion_retrieval in ControlNet example

---

.github/workflows/release.yaml
scripts/tag_components.sh

Apparently the ghcr doesn't automatically apply the `latest` tag. This PR now changes the flow to:
- Add git tag --> Build components and add version tag
- Turn git tag into github release --> Add `latest` tag to component with version tag

Tag images with latest during release

---

examples/pipelines/controlnet-interior-design/README.md
examples/pipelines/finetune_stable_diffusion/README.md

add fondant logo to example pipelines

add fondant logo to example pipelines

---

README.md
docs/component_spec.md
pyproject.toml

Small PR to improve the docs:
1) Replace emojis textual representation to Unicode characters (graphical representation) in order for them to render properly on pypi. Similar to HF transformers: 
https://raw.githubusercontent.com/huggingface/transformers/main/README.md
https://pypi.org/project/transformers/
2) Correct reference to github page on pypi: `project links -> homepage` references to a page that does not exist. Corrected this in the pyproject.toml (not sure if this translates to the pypi pages).

Improve pypi docs

---

components/caption_images/Dockerfile
components/caption_images/src/main.py
components/download_images/Dockerfile
components/download_images/src/main.py
components/embedding_based_laion_retrieval/Dockerfile
components/embedding_based_laion_retrieval/src/main.py
components/image_cropping/Dockerfile
components/image_cropping/src/main.py
components/image_embedding/Dockerfile
components/image_embedding/src/main.py
components/image_resolution_filtering/Dockerfile
components/image_resolution_filtering/src/main.py
components/load_from_hf_hub/Dockerfile
components/load_from_hf_hub/src/main.py
components/prompt_based_laion_retrieval/Dockerfile
components/prompt_based_laion_retrieval/src/main.py
components/segment_images/Dockerfile
components/segment_images/src/main.py
docs/custom_component.md
examples/pipelines/controlnet-interior-design/components/generate_prompts/src/main.py
examples/pipelines/controlnet-interior-design/components/write_to_hub_controlnet/src/main.py
fondant/component.py
fondant/component_spec.py
fondant/manifest.py
fondant/pipeline.py
tests/example_specs/component_specs/kubeflow_component.yaml
tests/test_component.py

PR that enables adding a custom component spec for each component as described in #174 
The implemented approach differs slightly from the described issue since we forgot to take into account that we need to parse the arguments twice. Once to retrieve the component spec and another time for the other arguments which include things like the `metadata` and `manifest` as well as use specific arguments (which are defined as part of the component spec)
* The component spec is now an exact match to the one passed to the pipeline. We no longer are defining it during the build process. This enables us to use dynamic specs. 
* We still keep the method `from_file()` method as this is used when building and compiling the pipeline. 
We still need to adapt the currently available read and write …

Custom component spec

---

components/embedding_based_laion_retrieval/fondant_component.yaml
components/image_embedding/fondant_component.yaml
components/segment_images/fondant_component.yaml
docs/component_spec.md
examples/pipelines/controlnet-interior-design/components/write_to_hub_controlnet/fondant_component.yaml
fondant/component_spec.py
fondant/exceptions.py
fondant/manifest.py
fondant/schema.py
fondant/schemas/common.json
tests/example_pipelines/invalid_pipeline/example_1/second_component.yaml
tests/example_pipelines/invalid_pipeline/example_2/second_component.yaml
tests/example_pipelines/valid_pipeline/example_1/second_component.yaml
tests/example_pipelines/valid_pipeline/example_1/third_component.yaml
tests/example_specs/component_specs/valid_component.yaml
tests/example_specs/evolution_examples/1/component.yaml
tests/example_specs/evolution_examples/1/output_manifest.json
tests/example_specs/evolution_examples/2/component.yaml
tests/example_specs/evolution_examples/2/output_manifest.json
tests/example_specs/evolution_examples/3/component.yaml
tests/example_specs/evolution_examples/3/output_manifest.json
tests/test_component_specs.py
tests/test_manifest.py
tests/test_schema.py

PR that addresses #178 
Inspiration: https://swagger.io/docs/specification/data-models/data-types/#:~:text=the%20null%20value.-,Arrays,-Arrays%20are%20defined (credit to @GeorgesLorre)
It includes: 
* Changing the common json schema to enable defining array types 
* Changing the `Type` class to be dynamic rather than typed to enable defining nested structures without explicitly defining them
* Adding an addition test file for `schema.py`
* Updating the current existing examples (embedding + segmentation)

Enable defining nested data types

---

docs/component_spec.md
fondant/component.py
fondant/component_spec.py
fondant/schemas/component_spec.json
tests/example_specs/components/arguments/component_default_args.yaml
tests/test_component.py

PR that enables adding default arguments as discussed in #179. 
Users can now define default arguments in the component specs. Those arguments do not have to be explicitly defined in the `ComponentOp` but could still be overridden.  
Note: please review this [PR](https://github.com/ml6team/fondant/pull/196) beforehand since I am branched off from it. 
Created a separate ticket to do the necessary changes #198. Best to handle it in a separate PR.

Enable default component arguments

---

components/embedding_based_laion_retrieval/src/main.py
components/prompt_based_laion_retrieval/src/main.py
docs/custom_component.md
fondant/component.py
tests/example_specs/components/input_manifest.json
tests/test_component.py

Fixes #204 
Unfortunately, wasn't able to propagate this through Dask. I got the Dask code to work with hierarchical columns as long as the index was not hierarchical, but I run into issues when trying to write this data to parquet.
So this means that only the pandas component gets hierarchical columns and I do the translation when we switch from Dask to Pandas.
I would propose to change our `_` for the flat column names to a symbol which we expect to be less frequently used in the names of data columns or fields. Eg. `images_data` could become `images+data` instead. This will have no impact on users using the `PandasTransformComponent`, but it will change for users using the `DaskTransformComponent` (which is not clear yet how much there would be).
Retrieving the data using hierarchical …

Provide hierarchical columns in pandas component

---

components/caption_images/requirements.txt
components/download_images/requirements.txt
components/embedding_based_laion_retrieval/requirements.txt
components/filter_comments/requirements.txt
components/filter_line_length/requirements.txt
components/image_cropping/requirements.txt
components/image_embedding/requirements.txt
components/image_resolution_filtering/requirements.txt
components/load_from_hf_hub/requirements.txt
components/pii_redaction/requirements.txt
components/prompt_based_laion_retrieval/requirements.txt
components/segment_images/requirements.txt
docs/custom_component.md
examples/pipelines/controlnet-interior-design/README.md
examples/pipelines/controlnet-interior-design/components/generate_prompts/requirements.txt
examples/pipelines/controlnet-interior-design/components/write_to_hub_controlnet/requirements.txt
examples/pipelines/starcoder/components/load_from_hub_stack/requirements.txt

PR to change the fondant version in the component build to the latest + update some docs to refer to installing fondant from the official pip package

Change default fondant version to latest and update docs

---

components/download_images/src/main.py
examples/pipelines/datacomp/components/filter_text_complexity/src/main.py
fondant/component.py

This PR filters out data from the pandas dataframe returned by the user that is not defined in the component spec. Previously, returning additional columns would raise an error. (see https://github.com/ml6team/fondant/pull/223#issuecomment-1602233930)

Don't validate returned Pandas dataframe strictly

---

fondant/compiler.py

If someone initializes the pipeline with a local base path and uses a relative path, `docker-compose up` will fail because the volume bindings require an absolute path.
To avoid this, I propose resolving the absolute path during the generation of the `docker-compose.yaml`.

Enforce binding of absolute path

---

.github/workflows/prep-release.yaml
.github/workflows/release.yaml

Fixes #255 
We were rebuilding the fondant package when publishing to PyPI, which doesn't follow the "build once" mantra, and we were already suffering the consequences. Our `build_components.sh` script updates the image version in the component spec of the reusable components, which are included in the fondant python package. However this script only runs in the pipeline pushing to test.PyPI, not in the actual release pipeline pushing to PyPI.
This PR now downloads the package from test.PyPI and pushes it to PyPI instead of rebuilding, which should fix this issue.
Since the pipelines diverged further, I split them into separate files and removed the conditionals.

Promote package from test.PyPI to PyPI without rebuilding

---

.github/workflows/build.yaml
.github/workflows/prep-release.yaml

[The prep-release pipeline failed](https://github.com/ml6team/fondant/actions/runs/5452193633) because the new build script requires buildx.

Install buildx in prep-release pipeline

---

scripts/build_explorer.sh

`buildx` doesn't save the manifest locally when building, so we need to push it in the same command.

Update build_explorer.sh to use buildx

---

examples/pipelines/commoncrawl/components/load_from_commoncrawl/Dockerfile
examples/pipelines/commoncrawl/components/load_from_commoncrawl/fondant_component.yaml
examples/pipelines/commoncrawl/components/load_from_commoncrawl/requirements.txt
examples/pipelines/commoncrawl/components/load_from_commoncrawl/src/main.py

This component is the first part of the commoncrawl pipeline. Given an index, this component loads the corresponding index file from the AWS Public Data Sets (S3 bucket) and returns a list of its WARC segment file paths as a dataframe.

[Commoncrawl pipeline] Add load from commoncrawl component

---

fondant/component.py
tests/test_component.py

Order output columns in PandasTransformComponent

---

fondant/compiler.py
fondant/pipeline.py
fondant/runner.py
tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_2/docker-compose.yml
tests/test_cli.py
tests/test_pipeline.py
tests/test_runner.py

Fixes #259 
This PR:
- Instructs the local runner to always pull images. This makes sure that moving tags like `dev` or `latest` are up to date before running the pipeline. As far as I can tell from my testing, this doesn't cause a noticeable delay when the image was not updated.
- Adds the pipeline name to the docker compose yaml and removes orphan containers. Containers are namespaced by the pipeline name, which defaults to the cwd if not specified. So I set the name explicitly so we don't accidentally remove containers from another pipeline.

Always pull images in local runner

---

pyproject.toml

I fixed a deprecation warning from `jsonschema` in #280. This means we are no longer compatible with `jsonschema` versions < 4.18.0, so we should bump it in the `pyproject.toml`.

Bump jsonschema version to 4.18.0

---

src/fondant/import_utils.py
tests/test_import_utils.py

PR that removes obsolete extra packages from `import_utils`

Remove obsolete packages

---

pyproject.toml

We use `fsspec` [directly](https://github.com/ml6team/fondant/blob/main/src/fondant/manifest.py#L10) in fondant, so we should add it as a dependency.

Add fsspec as explicit dependency

---

scripts/post-build.sh
scripts/pre-build.sh
src/fondant/components
tox.ini

This PR adds a `post-build.sh` script which reverts the actions of the `pre-build.sh` script and runs it after testing with tox to revert the original state of the src/fondant/components symlink.

Revert src/fondant/components after testing with tox

---

README.md
components/caption_images/src/main.py
components/download_images/src/main.py
components/embedding_based_laion_retrieval/src/main.py
components/filter_comments/src/main.py
components/filter_image_resolution/src/main.py
components/filter_line_length/src/main.py
components/image_cropping/src/main.py
components/image_embedding/src/main.py
components/image_resolution_extraction/src/main.py
components/language_filter/src/main.py
components/load_from_hf_hub/src/main.py
components/minhash_generator/src/main.py
components/pii_redaction/src/main.py
components/prompt_based_laion_retrieval/src/main.py
components/segment_images/src/main.py
components/text_length_filter/src/main.py
components/text_normalization/src/main.py
components/write_to_hf_hub/src/main.py
docs/component_spec.md
docs/custom_component.md
examples/pipelines/commoncrawl/components/load_from_commoncrawl/src/main.py
examples/pipelines/controlnet-interior-design/components/generate_prompts/src/main.py
examples/pipelines/datacomp/components/cluster_image_embeddings/src/main.py
examples/pipelines/datacomp/components/filter_text_complexity/src/main.py
src/fondant/component.py
src/fondant/executor.py
src/fondant/pipeline.py
tests/test_component.py

This PR follows up on the PoC presented in #268
---
Fixes #257 
It splits the implementation and execution of components, this has some advantages:
- Pandas components can use `__init__` instead of setup, which is probably more familiar to users
- Other components can use `__init__` as well instead of receiving all arguments to their transform or equivalent method, aligning implementation of different component types
- Component implementation and execution should be easier to test separately
I borrowed the executor terminology from KfP.
---
Fixes #203 
Since I had to update all the components, I also switched some of them to subclass `PandasTransformComponent` instead of `DaskTransformComponent`.
---
These changes open some opportunities for additional improvements, but I propose to …

Split component implementation and execution

---

src/fondant/executor.py
tests/example_specs/components/arguments/component.yaml
tests/test_component.py

Fixes default values set at `0` that were wrongly evaluated to `None`

Bugfix default 0 values

---

src/fondant/executor.py

Related to #313 
The local and remote runner store the manifest in different locations: 
* For the local runner, the manifest save path is set at compile time to a fixed path that we specify `{base_path}/{component_name}/manifest.json"`   
* For the remote runner (kfp), the `output_manifest_path` is set as an output artifact type. This is needed for chaining component together. The save path in this case is save internally within the VM `/tmp/outputs/output_manifest_path/data` and then mapped to minio storage after the component run (which then gets mapped to a cloud storage). The mapping saves the artifact to the specified base path followed by a fixed file structure that cannot be changed and also stored. It is also stored as zip file which contains the written text file (manifest) …

Unify manifest save path

---

src/fondant/executor.py

PR to read base path from the manifest instead of the metadata argument since we're not passing the metadata as an argument to every component

Bugfix basepath

---

.gitignore
scripts/build_components.sh

This PR ensures that the `build_components.sh` script can run on both Linux and MacOS.
As suggested by @RobbeSneyders [here](https://github.com/ml6team/fondant/pull/303#discussion_r1269909421), thanks!

[Scripts] Fix build_components

---

docs/pipeline.md
src/fondant/pipeline.py
tests/test_pipeline.py

This PR adds a configurable node pool label in the pipeline specification. This is needed because the default label name differs per cloud provider.

Add node pool label

---

components/download_images/fondant_component.yaml
components/filter_image_resolution/fondant_component.yaml
components/image_cropping/fondant_component.yaml
components/image_resolution_extraction/fondant_component.yaml
examples/pipelines/datacomp/components/cluster_image_embeddings/fondant_component.yaml
examples/pipelines/datacomp/components/load_from_hf_hub/fondant_component.yaml
src/fondant/schemas/common.json
tests/example_pipelines/compiled_pipeline/example_2/docker-compose.yml

When running the Datacomp pipeline at scale, I encountered an outlier image which had a width of about 37,000 pixels. As the component was using int16 as the dtype of the width column, this failed as it was outside the range. The error suggested to use int64 instead.
Then I noticed int64 is not supported yet, hence this PR adds it.

Add int64 dtype

---

pyproject.toml

Add constrain to KFP version to avoid downloading latest by default (v2) which has a different API

Add kfp constraint

---

components/filter_image_resolution/fondant_component.yaml
examples/pipelines/datacomp/components/filter_text_complexity/fondant_component.yaml
examples/pipelines/datacomp/components/load_from_hf_hub/fondant_component.yaml
examples/pipelines/datacomp/pipeline.py
scripts/build_components.sh

This PR updates the pipeline name of DataComp, and makes sure it can run fine both locally and on GCP.
Switching between local vs GCP is currently done as follows:
- I need to manually comment out the base path I don't want to use
- it's either running `fondant run pipeline:pipeline --local` or `python pipeline.py`

[DataComp] Update pipeline name, remove DockerCompiler

---

src/fondant/data_io.py

Since version 2023-7-1, Dask DataFrames automatically convert object data types to string[pyarrow] ([changelog](https://docs.dask.org/en/stable/changelog.html#v2023-7-1))
This leads to `Dask` trying to read image data as strings, which results in the following error:
> unicodedecodeerror: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
---
I tried several things to force Dask to keep this data as bytes:
- Write metadata file with schema in `to_parquet`
- Cast to bytes explicitly after reading using `read_parquet.astype(...)`
But none of these worked. I believe this is because `pandas` represents binary data using the `object` dtype, which is then automatically converted to string by `Dask`.
---
So I believe our only option is to deactivate this behavior completely: …

Deactivate dask string conversion

---

examples/pipelines/controlnet-interior-design/pipeline.py
examples/pipelines/finetune_stable_diffusion/pipeline.py

Our current example pipelines don't work anymore out of the box since https://github.com/ml6team/fondant/pull/327 requires `node_pool_label` and `node_pool_name` to either both be set, or neither.
This PR removes the `node_pool_name` since it is very specific to our own kfp cluster anyway.

Remove node_pool_name arguments in examples

---

tox.ini

Had issues running tox locally which in the end were unrelated to the configuration. But in the meantime I learned some better practices for tox, which I implemented in this PR.

Small improvements to tox configuration

---

src/fondant/compiler.py
src/fondant/runner.py
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml
tests/test_runner.py

PR implementing the Kfp runner.
Had some issues with adding the pipeline name to the kfp spec (solved now) because we need it to launch a run with a sensible name.
Remarks:
- removed some logic around deleting existing pipelines that we have (which was not used afaik)
- I tested it on a toy pipeline and was able to push a run on the GCP kubeflow
- I will implement the CLI (for both the runner and compiler) in a separate PR 
- I will also make a separate PR for cleaning up the kfp imports and extras.

Implement kfp runner with tests

---

.pre-commit-config.yaml
examples/pipelines/commoncrawl/components/extract_image_licenses/src/utils/image_utils.py
pyproject.toml

To avoid security breaches bandit should scan the pipeline example folders and tests as well.

Adjust bandit settings

---

src/fondant/component_spec.py
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml
tests/example_specs/component_specs/kubeflow_component.yaml

PR that modifies the KFP command to contain the new fondant cli command used to execute the component

Modify kfp command

---

components/load_from_hf_hub/src/main.py
examples/pipelines/finetune_stable_diffusion/pipeline.py

A fix for loading the dataset when `n_rows_to_load` is specified. An offset of 1 was missing which caused an issue when there was only 1 partition (npartitions from the enumerate started from 0 and an attempt to call `df.head()` with 0 partitions was made)

Bugfix partitions Load from Hub

---

src/fondant/compiler.py
tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/test_compiler.py

PR that adds GPU resource for the local runner when specified in the componentOP 
based on: 
https://docs.docker.com/compose/gpu-support/

Enable GPU for local runner

---

components/download_images/src/main.py

This should solve a lot of the "invalid non-printable ASCII character in URL" errors

Strip url in download_images before downloading

---

src/fondant/compiler.py
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml

PR that adds missing nodepool label from the compiler. The label was defaulted to `node_pool` which currently only applies to GCP.

Add missing nodepool label

---

docs/pipeline.md
src/fondant/compiler.py
src/fondant/executor.py
src/fondant/filesystem.py
src/fondant/manifest.py
src/fondant/pipeline.py
tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml
tests/example_specs/components/arguments/input_manifest.json
tests/example_specs/mock_base_path/example_pipeline/example_pipeline_2022/component_1/manifest_1.json
tests/example_specs/mock_base_path/example_pipeline/example_pipeline_2022/component_2/manifest_2.json
tests/example_specs/mock_base_path/example_pipeline/example_pipeline_2023/component_1/manifest_1.json
tests/example_specs/mock_base_path/example_pipeline/example_pipeline_2023/component_2/manifest_2.json
tests/test_compiler.py
tests/test_component.py
tests/test_filesystem.py
tests/test_manifest.py
tests/test_pipeline.py

PR that implements caching: 
* The component cache is estimated at compile time based on the images tag, input parameters, component spec and component resources (GPU, nodepool). Caching is enabled by default at the componentOp level and disabled if the image has the `latest` tag
* At runtime, the cache key is checked against the base path to check for matching executions based on a the cache key (currently appended to the manifest name). 
*  If multiple matching executions are found, we return the latest one. This makes it easier to develop. For example, if we're working with the `dev` tag and we disable caching to force the execution of a new version of the component (scenario where the spec and parameters are the same). Then when we enable caching again, we would only load the manifest …

Implement caching

---

src/fondant/executor.py
src/fondant/manifest.py
tests/test_component.py
tests/test_data_io.py
tests/test_manifest.py

PR that standarizes ffspec file access to use the `Abstractfilesystem` class for all filesystem related functionalities. 
Previously we were using the `Abstractfilesystem` and custom functions `fs_open()` to read/write/list the manifest(s). This caused some issue since `fs_open` expects the protocol of the file system to be present in the URL. However, files returns by `Abstractfilesystem().ls` returned a normal file system url. When passed to `fs_open()` it causes it to fail to read the file properly.
Still some issues with using glob patterns. More details here: https://github.com/ml6team/fondant/issues/368

Standarize fsspec file access

---

src/fondant/cli.py

When compiling with the CLI, both the local runner and remote yaml files had the name `docker-compose.yml`. 
This PR sets different defaults depending on the runner type

Correct default pipeline output

---

src/fondant/cli.py
tests/test_cli.py

Fixes bug that was encountered by @NielsRogge. Issue was that the runner default output was added to the compiler only and not the runner.

Add output default to cli runner

---

docs/pipeline.md
src/fondant/compiler.py
src/fondant/pipeline.py
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/test_compiler.py

PR that adds an option to set a preemptible VM on the component spec level. 
This can be done by setting `preemptible` to True at the `Op` level. Note that you also need to assign a preemptible nodepool. I have already setup some preemptible nodepools in [this PR](https://github.com/ml6team/Express-infra/compare/add-preemtibles-node-pools?expand=1) 
Caveat: seems like kfp currently only enables setting up preemptibles on a GCP cluster since this functionaliteis seems to be tightly integrated with GKE. More info [here](
Preemptible nodepools can only run up to 24 hours [link](https://cloud.google.com/compute/docs/instances/preemptible#:~:text=Compute%20Engine%20always%20stops%20preemptible%20instances%20after%20they%20run%20for%2024%20hours.%20Certain%20actions%20reset%20this%2024%2Dhour%20 …

Add option to setup preemptible VMs

---

components/load_from_hf_hub/src/main.py

PR that fixes an issue with the load from hub component when setting an index dynamically. Previous implementation relied on estimating the `meta/schema` dynamically but this lead to some errors since sometimes the wrong type was inferred. 
This PR fixes this issue by reading in the schema from the component spec

change meta estimation

---

.github/workflows/pipeline.yaml
pyproject.toml
src/fondant/runner.py
tests/test_runner.py

adresses: https://github.com/ml6team/fondant/issues/417

Add vertex runner

---

docs/pipeline.md
examples/pipelines/controlnet-interior-design/pipeline.py
examples/pipelines/datacomp/pipeline.py
examples/pipelines/finetune_stable_diffusion/pipeline.py
pyproject.toml
src/fondant/compiler.py
src/fondant/component_spec.py
src/fondant/pipeline.py
tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_1/vertex_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/vertex_pipeline.yml
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml
tests/example_specs/component_specs/kubeflow_component.yaml
tests/test_compiler.py
tests/test_pipeline.py

PR that adds option to set hardware accelerators to KFP V2 (nodepool 
Notes: 
* Each component was previously configured as a sub-pipeline because of an error in detecting a certain field in the V2 spec (`exec-<sanitizied_component_name`) which forces to kubeflow to compile component to a pipeline spec instead of a component spec [link](https://github.com/kubeflow/pipelines/blob/ad058b5321f5fe74bbd10845778e6627fb9aa5cb/sdk/python/kfp/dsl/structures.py#L462). This was resolved by adding the same custom method used by KFP to format the component name to Fondant.
This makes it possible to assign resources to each component since KFP does not allow assigning resources on a pipeline level 
* Setting up and running nodepools is still to be tested on native KFP

Add hardware configs

---

components/download_images/fondant_component.yaml
docs/component_spec.md
src/fondant/compiler.py
src/fondant/component_spec.py
src/fondant/executor.py
src/fondant/pipeline.py
src/fondant/schemas/component_spec.json
tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_1/vertex_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/vertex_pipeline.yml
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml
tests/example_specs/component_specs/kubeflow_component.yaml
tests/example_specs/components/arguments/component.yaml
tests/example_specs/components/arguments/component_default_args.yaml
tests/test_compiler.py
tests/test_component.py

PR that fixes the v2 default /optional types. KFP v2 has two different optional types: 
- Optional values that default to None -> defined by setting `isOptional` to True and not passing the default value
- Optional values that default to another values  -> defined by setting the value in  `defaultValue` and having `isOptional` False or empty. 
This PR adjusts the componentSpec accordingly. Another nice win is that we do not have to define bools/dicts/lists as strings in the component spec 
Few things no note: 
* Due to strict type. Mixing different data types is not allowed -> we had to change the type of `input_partition_rows` to int. Which means it does not accept the value `disable` anymore. Need to fix this in a seperate PR 
* 'inf` as float is not allowed

Fix v2 defaults

---

src/fondant/component_spec.py
src/fondant/executor.py
src/fondant/pipeline.py
tests/example_pipelines/compiled_pipeline/example_1/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/docker-compose.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/kubeflow_pipeline.yml
tests/example_specs/component_specs/kubeflow_component.yaml

Still, there might be some issues with the usage of the dask client and local cluster. To make it more intuitive, we should revert to using the old way as the default. This PR sets the old way as the default option, and the client usage will now need to be set explicitly.

Set dask local scheduler as default

---

src/fondant/executor.py
src/fondant/manifest.py

There was a change of the default behaviour in the recent fsspec release (2023.9.1)
Use the `auto_mkdir` in fs_open to utilize automatic directory creation. 
Solves #440

Use auto_mkdir in fs_open calls

---

src/fondant/explorer.py
tests/test_explorer.py

Small PR that: 
- Add pull always policy to the data explore. @Hakimovich99 ran into some issues where the latest image was not pulled (False positive in caching since we're using the `latest` tag)
- Fixes issue that @janvanlooy ran into that's related to the volume mounting. Related to Windows (still to be tested if fix actually resolves the issue). 
https://stackoverflow.com/questions/50540721/docker-toolbox-error-response-from-daemon-invalid-mode-root-docker

Small fixes explorer

---

src/fondant/compiler.py
src/fondant/pipeline.py
tests/test_compiler.py

PR that enables assigning additional resources to Vertex (CPU/RAM)
https://cloud.google.com/vertex-ai/docs/pipelines/machine-types
1) Setting name of the compute instance directly using a custom job as specified [here](https://cloud.google.com/vertex-ai/docs/pipelines/request-gcp-machine-resources). This does not work well because it ended up changing the structure of the compiled spec entirely and uses a custom docker image by default. I also ran into a bug that forced me to specify it outside of the compilation decorartor https://github.com/kubeflow/pipelines/issues/9320 which can be a bit ugly (Required looping through the components twice) 
2) Specifying the requested resources as mentioned [here](https://cloud.google.com/vertex-ai/docs/pipelines/machine-types) This seems like a …

Enable defining additional Vertex Resources

---

examples/pipelines/filter-cc-25m/pipeline.py

Disable caching in the example pipeline.

Disable caching in the image retrieval sample pipeline

---

components/download_images/src/main.py

Some of the exception caught by the download images component returned an empty string since the exception object does not always have a **string representation** .
Example:
```python
except Exception as e:
logger.warning(f"Skipping {url}: {e)")
```
returns: 
```bash
Skipping https://2.gravatar.com/avatar/2d7699b189a0d1e40a506aa3b8cad2dc?s=48&d=identicon&r=G: 
```
This makes it difficult to trace back why a url was skipped. Changing to `repr(e)` seems to fix it since most exeception objects seem to have a **printable representational string** (at least the httpx ones)

Improve download images logs

---

components/load_from_parquet/Dockerfile
components/load_from_parquet/fondant_component.yaml
components/load_from_parquet/src/main.py
examples/pipelines/datacomp/pipeline.py

PR that creates a generic component to load data stored as a parquet from remote storage 
Largely based on the load from hub component with some modification. Currently needed for the datacomp pipeline. 
Future modification could include loading data from local storage though we'd need to make sure that the data is mounted locally

Create load from parquet

---

src/fondant/compiler.py
src/fondant/pipeline.py
tests/test_compiler.py

Current implemented caching does not take into account the previous component cache key when estimating the cache key. This can be an issue in some scenarios, for example: 
**1st run:** load_from_hub (input_dataset=x) -> download_images
**2nd run:** load_from_hub (input_dataset=y) -> download_images
In the second run, the download images component won't execute and will be cached since it might have the same input arguments as the first run. However, both runs start from different input datasets and thus the second run would actually end up loading in the dataset cached from the 1st run. 
This PR addresses this by including the hash key of the dependent component in the component cache key estimation.

Add caching dependency

---

components/download_images/fondant_component.yaml
components/download_images/src/main.py

This PR contains two changes to improve the hit rate of the download images component:
- Introduce a Semaphore to limit the amount of concurrent requests. This should help with the timeout errors. If this slows down the speed too much, we can increase the number. If the changes in this PR work, we probably want to make this an argument to the component.
- Configure httpx to follow redirects, [which it doesn't do by default](https://www.python-httpx.org/compatibility/#redirects), but requests / urllib3 does.

Improve hit rate of download images component

---

components/embedding_based_laion_retrieval/src/main.py
components/prompt_based_laion_retrieval/src/main.py
examples/pipelines/controlnet-interior-design/components/generate_prompts/fondant_component.yaml

PR that cast id to string in the laion component. 
Not really sure why Dask expects a string as an ID? Seem to be the default behavior. We don't define the type of index explicitly in the schema since it can be either a string or an integer depending on the what the user or Fondant sets as an index. 
More on this: 
https://github.com/ml6team/fondant/pull/391#discussion_r1308294201
```
controlnet-pipeline-laion_retrieval-1   | [2023-10-04 13:22:52,375 | fondant.cli | INFO] Component `LAIONRetrievalComponent` found in module main
controlnet-pipeline-laion_retrieval-1   | [2023-10-04 13:22:52,377 | fondant.executor | INFO] Dask default local mode will be used for further executions.Our current supported options are limited to 'local' and 'default'.
controlnet-pipeline-laion_retrieval-1   | …
```

Cast id to string laion

---

src/fondant/data_io.py
tests/test_data_io.py

The number of partitions set based on the number of specified rows per partition (optional argument) did not take into account the number of available cpu cores which can be suboptimal if the # cores is larger than the inferred number of estimated partitions. 
This PR addresses this bug by taking into account the number of cores before repartitioning

Bugfix partitioning

---

src/fondant/explorer.py
tests/test_explorer.py

use as_posix to return the absolute path. Avoids denied mounting issue when calling the explorer.

explorer small fix

---

components/caption_images/src/main.py
components/embed_images/src/main.py
components/segment_images/src/main.py
examples/pipelines/datacomp/components/detect_text/src/main.py
examples/pipelines/datacomp/components/mask_images/src/main.py

PR that modifies all current GPU components by:
* Batching both the preprocessing and inference to avoid OOM issues
* Disabling a pytorch API that caused **illegal memory access issues**. More on this issue [here](https://github.com/pytorch/pytorch/issues/99372)

Optimize GPU components

---

examples/pipelines/commoncrawl/components/extract_images_from_warc/requirements.txt
examples/pipelines/commoncrawl/components/extract_images_from_warc/src/main.py
examples/pipelines/commoncrawl/components/extract_images_from_warc/src/utils/download_utils.py
examples/pipelines/commoncrawl/pipeline.py

Update the Common Crawl download and image extraction component to utilise S3 instead of HTTP requests.
Solving #497

Use s3 client instead of http to access common crawl

---

src/fondant/cli.py

The `run` command was broken in #488. This fixes it by adding the `ref` argument to the subparsers separately.

Fix run CLI

---

src/fondant/cli.py
src/fondant/runner.py
tests/test_cli.py
tests/test_runner.py

PR that adds functionalities for compiling and running Vertex Pipelines with the CLI. 
After this PR is merged, i'd like to simplify a bit the compilation for both vertex and compile since there is a lot of repetition #517

Vertex cli

---

src/fondant/compiler.py

PR that refactors the compiler module:
* `set_configuration()` is added as an abstract method since it's implemented in all of the compilers
* Since kfp and vertex have the same compile method, the `compile()` method is now defined in the kfp compiler and the vertex compiler is now it's child class. Other methods like `resolve_imports()` and `set_configuration` are overridden

Refactor compile method for kfp and vertex

---

examples/pipelines/commoncrawl/components/extract_images_from_warc/Dockerfile
src/fondant/component_spec.py
src/fondant/executor.py
tests/example_pipelines/compiled_pipeline/example_1/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_1/vertex_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/kubeflow_pipeline.yml
tests/example_pipelines/compiled_pipeline/example_2/vertex_pipeline.yml
tests/example_specs/component_specs/kubeflow_component.yaml

This PR addresses 2 issues:
- The `client_kwargs` argument was not propagated properly and couldn't be used
- Python 3.11 leads to very long dependency resolution times with KfP and aiplatform dependencies

Propagate `client_kwargs` argument and lower extract_images python version

---

src/fondant/compiler.py
src/fondant/pipeline.py
tests/example_pipelines/compiled_pipeline/example_1/vertex_pipeline.yml

This was necessary to be able to allocate enough memory. Added the missing ones to the KfP compiler as well.
Proof that it works: https://console.cloud.google.com/vertex-ai/locations/europe-west1/pipelines/runs/datacomp-filtering-pipeline-20231017201538?project=soy-audio-379412

Add resource limits for Vertex

---

pyproject.toml
src/fondant/build.py
src/fondant/cli.py
src/fondant/component_spec.py

Fixes #249 
Please test this on your local machine when reviewing :)

Add fondant build command

---

scripts/build_explorer.sh
scripts/tag_components.sh
scripts/tag_explorer.sh

The release pipeline fails on building the explorer script. It was not properly updated for our switch to DockerHub.
Works now: https://hub.docker.com/r/fndnt/data_explorer

Fix explorer build script for DockerHub

---

src/fondant/cli.py
src/fondant/runner.py
tests/test_cli.py

This is needed to access private IPs from Vertex pipelines (eg. a private Weaviate endpoint).

Add network argument to vertex runner

---

src/fondant/cli.py

Fixes error with wrong error being propagated when using any of the runners with the CLI: 
before:
```bash
❯ fondant run local pipeline.py --extra-volumes "$HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro"
Traceback (most recent call last):
File "/home/philippe/Scripts/express/src/fondant/cli.py", line 479, in run_local
pipeline = pipeline_from_module(args.ref)
File "/home/philippe/Scripts/express/src/fondant/cli.py", line 605, in pipeline_from_module
module = get_module(module_str)
File "/home/philippe/Scripts/express/src/fondant/cli.py", line 595, in get_module
module = importlib.import_module(module_str)
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return …
```

Fix cli error propagation

---

data_explorer/app/widgets.py
docs/data_explorer.md
docs/pipeline.md
src/fondant/cli.py
tests/test_cli.py

Simplify cloud credentials mounting

---

mkdocs.yml

I believe this will fix the 404 pages on the deployed website.
It's unfortunately not possible to test this with mkdocs serve / PR builds since the canonical base url is different. However, if you inspect the requests used to load the assets, you can see it now uses `/en/latest/<asset>` instead of `/<asset>`, which should work when deployed on the main site.
[Relevant ReadTheDocs docs](https://docs.readthedocs.io/en/stable/reference/404-not-found.html)

Set mkdocs site_url to fix 404 page

---

src/fondant/pipeline/compiler.py
src/fondant/testing.py

Assign pipeline description label at the service level since labels can't be assigned at the root level

Fix pipeline label

---

docs/caching.md

Add more info about caching

---

docs/guides/installation.md

Addresses #599 
I think referencing the docker installation docs rather than pasting few snippets is better in our case since we don't require anything custom compared to airflow

Expand docker installation guide

---

src/fondant/build.py
src/fondant/cli.py
tests/test_cli.py

We could use `fondant build` in the cicd pipeline for building the component images. Add a parameter to enable the cli adding the label. 
Needed for [#5](https://github.com/ml6team/fondant-usecase-RAG/pull/5/files)

Add label argument to fondant build

---

pyproject.toml

Since this fails on incompatible type ignore statements

Skip followed imports for referencing.jsonschema

---

src/fondant/cli.py
tests/test_cli.py

The cloud credential arguments were only present to the `compile` command and not the `run` one. This PR fixes this issue, @Hakimovich99

Add authentification arg to run command

---

data_explorer/requirements.txt

The release pipeline failed because of version conflicts:
https://github.com/ml6team/fondant/actions/runs/6928655402/job/18844856836

Remove explicit fsspec requirements from data explorer

---

.github/workflows/prep-release.yaml

The pipeline was not triggered by my `0.8.dev0` tag, which is the [recommended format](https://packaging.python.org/en/latest/specifications/version-specifiers/#developmental-releases) for development releases.

Update tag pattern in prep-release pipeline to match dev versions

---

src/fondant/component/data_io.py
tests/component/test_data_io.py

The output dataframe was not written to the correct path:
It might make sense to centralize this functionality somewhere, but not sure where.

Fix output dataframe path

---

src/fondant/cli.py

As discussed in https://github.com/ml6team/fondant-usecase-RAG/pull/25

Set default explorer version to current Fondant version

---

src/fondant/pipeline/runner.py
tests/pipeline/test_runner.py

Same as for the docker runner except its uglier

Augment SagemakerRunner to support running from pipeline objects

---

src/fondant/pipeline/compiler.py
src/fondant/pipeline/pipeline.py
tests/examples/example_modules/invalid_double_pipeline.py
tests/examples/example_modules/pipeline.py
tests/integration_tests/sample_pipeline_test/components/dummy_component/README.md
tests/integration_tests/test_sample_pipeline.py
tests/pipeline/test_compiler.py
tests/pipeline/test_pipeline.py
tests/pipeline/test_runner.py
tests/test_cli.py

This PR is the first one of multiple PRs to replace #665. This PR only focuses on implementing the new pipeline interface, without adding any new functionality.
The new interface applies operations to intermediate datasets instead of adding operations to a pipeline, as shown below. It's a superficial change, since only the interface is changed. All underlying behavior is still the same.
The new interface fits nicely with our data format design and we'll be able to leverage it for interactive development in the future. We can calculate the schema for each intermediate dataset so the user can inspect it. Or with eager execution, we could execute a single operation and allow the user to explore the data using the dataset.
I still need to update the README generation, but I'll do that as a …

Move to datasets & apply interface

---

README.md

fixed wrong link to "creating your first pipeline". This resulted in a 404 error before.

bugfix old getting started link that had 404 error

---

data_explorer/app/config.py
data_explorer/app/interfaces/common_interface.py
data_explorer/app/main.py

Bugfix to only show runs that have existing manifests in them in the explorer.

Explorer improve filtering of available runs

---

src/fondant/explore.py

Follow-up on #681 which fixes this for the Python SDK as well.

Set default explorer version in python sdk

---

.github/workflows/build.yaml
.github/workflows/prep-release.yaml
.github/workflows/release.yaml
scripts/tag_components.sh

The [prep-release pipeline failed](https://github.com/ml6team/fondant/actions/runs/7086335306) since it uses the `build_component.sh` script but doesn't login to AWS.
This PR fixes that.
I did not update the release pipeline. It uses the `tag_components.sh` script, which adds a `latest` tag to the version being released. We would need to update the script to enable updating the ECR tag as well. But
- I don't think we're actually using the `latest` tag anywhere
- The `latest` tag would raise additional issues with the pull-through cache, since it's cached
So I propose to leave it as is for now.

Build to AWS ECR on release

---

src/fondant/cli.py
tests/examples/example_modules/pipeline.py
tests/test_cli.py

In our RAG use case, [we want to start using a pipeline factory function](https://github.com/ml6team/fondant-usecase-RAG/pull/34#discussion_r1414114415), but this is currently not supported by the CLI.
This PR fixes that.
I also included a change (the first commit) which removes the `finally` blocks. We were using this as follows:
```python
try:
ref = ...
except SpecificError:
ref = ...
finally:
run(ref)
```
But apparently the `finally` block is also entered if any non-`SpecificError` exception is raised in the `try` block. This lead to all non-handled errors to become an `UnboundLocal` error. This is now no longer the case, and the original error is not caught.

Support pipeline factory functions as CLI reference

---

src/fondant/cli.py
src/fondant/pipeline/compiler.py
src/fondant/pipeline/pipeline.py
src/fondant/pipeline/runner.py
tests/pipeline/test_runner.py
tests/test_cli.py

You can now define resources on a component level for SageMaker:
```
images = raw_data.apply(
"download_images",
arguments={
"input_partition_rows": 100,
"resize_mode": "no",
},
resources=Resources(instance_type="ml.t3.xlarge"),
)
```
Only the instance_type is supported for SageMaker (for now)

Add support for resources with Sagemaker

---

.pre-commit-config.yaml
components/write_to_hf_hub/README.md
components/write_to_hf_hub/fondant_component.yaml
scripts/component_readme/generate_readme.py

This was temporarily deactivated since the specification on the main branch was out of sync. We still need to update the generic components to generate a more useful README, but that's for a separate PR.
Devs will need to reset their local pre-commit environments for this to work.

Reactivate readme generation pre-commit

---

components/embed_text/src/main.py

Set the environment key before calling the embedding model to avoid "no api key found" error.

Fix environment variable setting in embed_text component

---

components/index_weaviate/requirements.txt
components/index_weaviate/src/main.py
tests/component/test_component.py

Add logs to give indication on indexing progress

Add logs to weaviate

---

docs/data_explorer.md
docs/guides/build_a_simple_pipeline.md
docs/guides/first_pipeline.md
src/fondant/cli.py
src/fondant/core/schema.py
src/fondant/explore.py
src/fondant/pipeline/compiler.py
src/fondant/testing.py
tests/pipeline/test_compiler.py
tests/test_explorer.py

Small PR to avoid showing the localhost url before the image is build

Make data explorer non-blocking with docker compose

---

docs/components/component_spec.md
docs/documentation_guide.md

Fixes #730 
* Removed the `generic_component.md` page and reference
* Updated the `component_spec.md` file to reflect the new architecture design + include explanations on how to define dynamic fields with some examples + references to practical examples
* Removed outdated manifest examples
* Link to user to stumble on dynamic field sections: `documentation_guide -> building custom_components -> component_spec`

Include information on dynamic fields

---

components/load_from_csv/src/main.py
components/load_with_llamahub/src/main.py
src/fondant/component/data_io.py
src/fondant/component/executor.py
src/fondant/core/component_spec.py
src/fondant/core/manifest.py
src/fondant/pipeline/pipeline.py
tests/component/test_component.py
tests/core/examples/component_specs/generic_consumes_produces.yaml
tests/core/examples/component_specs/kubeflow_component.yaml
tests/core/test_component_specs.py
tests/core/test_schema.py

Fixes #728 
We now construct the operation spec once during the compilation process, serialize it and pass it to the component as an argument. No need to pass in the `produces` and `consumes` arguments anymore. 
Some attributes like the arguments and the previous index that are part of the component spec can still be accessed through the operation spec since the component spec is it's attribute.

Unify operation and component spec

---

components/chunk_text/fondant_component.yaml
src/fondant/core/manifest.py
src/fondant/core/schema.py
src/fondant/core/schemas/manifest.json
src/fondant/pipeline/__init__.py
src/fondant/pipeline/pipeline.py
tests/pipeline/test_compiler.py
tests/pipeline/test_pipeline.py

This PR propagates the dataset schema eagerly when an operation is applied. This is useful for iterative development in a notebook, since the schema of the current dataset can be inspected.
Result:
```
In [2]: from fondant.pipeline import Pipeline
In [3]: import pyarrow as pa
In [4]: pipeline = Pipeline(name="my-pipe", base_path="data")
In [5]: text_data = pipeline.read(
...:     "load_from_hf_hub",
...:     arguments={
...:         "dataset_name": "wikitext@~parquet",
...:         "n_rows_to_load": 1000,
...:     },
...:     produces={
...:         "text": pa.string(),
...:     },
...: )
In [6]: text_data.fields
Out[6]: {'text': Field({'name': 'text', 'type': Type(DataType(string)), 'location': '/my-pipe-20231227152908/load_from_hugging_face_hub'})}
In [7]: chunk_data = text_data.apply( …
```

Propagate dataset schema eagerly

---

src/fondant/core/exceptions.py
src/fondant/pipeline/argument_inference.py
tests/pipeline/test_argument_inference.py

Fixes #751 
This PR introduces functionality to infer the arguments from a `Component` class. The result is a dictionary with the argument names as keys, and `Argument` instances as values, which is the format of [`component_spec.args`.](https://github.com/ml6team/fondant/blob/8e828441eec8ff91074e5c8ccf16fe405b719594/src/fondant/core/component_spec.py#L193)
We can leverage this behavior for Lightweight Python components as described in #750.
Did some TDD here, let me know if I missed any cases.

Add component argument inference

---

components/evaluate_ragas/README.md
components/evaluate_ragas/fondant_component.yaml
components/evaluate_ragas/src/main.py
components/index_aws_opensearch/README.md

Fix to issue that @mrchtr raised
* `model_name` was actually referring to the class name used to import the model which can be `OpenAI` or `ChatOpenAI`. This caused some issues because we were trying to set `model_name` to `gpt-4`. Changed the arguments and default to reflect that. 
* ChatOpenAI seems to be the new default of defining models, changed the default model class to that one 
When initializing GPT-4 with `OpenAI()`:
```
UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain_community.chat_models import ChatOpenAI`
```
Also how it's set in RAGAS [LINK](https://docs.ragas.io/en/latest/howtos/customisations/llms.html#:~:text=Copy%20code-,from%20langchain.chat_models%20import%20ChatOpenAI,-gpt4%20%3D% …

Fix ragas component

---

components/index_aws_opensearch/src/main.py
components/index_qdrant/src/main.py
components/index_weaviate/src/main.py
components/retrieve_from_weaviate/src/main.py

**Weaviate:** https://github.com/weaviate/weaviate-python-client/blob/fa28abb55c96c0e1034d1c24cc1780f25a369ad4/weaviate/client.py#L295C1-L298C37
**Qdrant:** https://github.com/qdrant/qdrant-client/blob/6d019e67a133bea87a96bce388f5b901cdae1287/qdrant_client/qdrant_client.py#L131
**Opensearch:** https://github.com/opensearch-project/opensearch-py/blob/2ab3a40307d23a63d83977aa3adf146b6f02b5fa/opensearchpy/client/__init__.py#L254
ClipClient does not have an implement method 
https://github.com/rom1504/clip-retrieval/blob/37e482b99ee36fe51aa4f8ab1e6930dc809edb6d/clip_retrieval/clip_client.py#L17

Add teardown method to components

---

docs/runners/local.md
src/fondant/cli.py
src/fondant/core/schema.py
src/fondant/explore.py
src/fondant/pipeline/compiler.py
src/fondant/pipeline/runner.py
tests/pipeline/test_compiler.py
tests/test_cli.py
tests/test_explorer.py

The arguments that enabled authenticating to different clouds through volume mounting credentials were restricted to the CLI and were not explicitly available in the SDK.
This PR that moves the argument for authenticating to one of the clouds in the DockerRunner for the CLI to the SDK 
e.g 
authenticating to gcp 
```python
runner.run(auth_gcp=True)
```

Move cloud auth to sdk

---

examples/sample_pipeline/pipeline.py
examples/sample_pipeline/run.sh
src/fondant/pipeline/compiler.py
src/fondant/pipeline/lightweight_component.py
src/fondant/pipeline/pipeline.py
tests/pipeline/test_python_component.py

Add support to run lightweight python components in docker runner

---

components/index_weaviate/fondant_component.yaml
components/retrieve_from_weaviate/README.md
components/retrieve_from_weaviate/fondant_component.yaml
components/retrieve_from_weaviate/src/main.py
components/retrieve_from_weaviate/tests/test_component.py

Fixes https://github.com/ml6team/fondant-usecase-RAG/issues/70
* No need to specify the vectorizer and it's module (needed for embedding the hybrid search query), it will automatically use the one specified in the indexing component based on the initial schema. 
* Tested the functionality indirectly,
* Small fixes to default args of the indexing component

Enable hybrid search

---

components/index_weaviate/fondant_component.yaml
components/retrieve_from_weaviate/README.md
components/retrieve_from_weaviate/fondant_component.yaml
components/retrieve_from_weaviate/src/main.py
components/retrieve_from_weaviate/tests/test_component.py

Fixes https://github.com/ml6team/fondant/pull/796
Component that enables reranking. 
Reranking seems to currently only support text prompts, for this reason the retrieval component (similar to the recent changes to the indexing) now supports accepting both embeddings and text for the retrieval prompt

Enable reranking

---

docs/components/custom_containerized_component.md
docs/guides/implement_custom_components.md

Still going to test the full guide to ensure it is working properly.
I've reduced the guide for the custom component to a minimal description to keep it simple. For more advanced concepts, I refer to other parts of the documentation.
fix #807

Update getting started guide

---

src/fondant/component/executor.py
tests/component/test_component.py

Fixes https://github.com/ml6team/fondant/issues/813

Enable write components to cache

---

docs/components/lightweight_components.md

Update lightweight docs based on https://github.com/ml6team/fondant/pull/789

Update lightweight docs

---

README.md

Based on a discussion on discord, we should update the fondant install command in our readme.

Update fondant install command in the readme

---

docs/guides/build_a_simple_pipeline.md
docs/guides/implement_custom_components.md

Added `write_to_file` to both getting started guides. #826 already added the component to the example pipeline.
fix #825

Add reusable write to file component to getting started examples

---

pyproject.toml
src/fondant/pipeline/lightweight_component.py

When running the lightweight components in a notebook, the component class code inspection fails with error `source code is not available`. 
Full error log here [log.txt](https://github.com/ml6team/fondant/files/14114022/new.3.txt)
The error is related to the fact that `inspect` relies on the class located in a source file which is not the case in a notebook where everything runs interactively. This is described in details [here](https://stackoverflow.com/questions/35854373/python-get-source-code-of-class-using-inspect#:~:text=getsource%20works%20by%20actually%20opening%20the%20source%20file%20that%20defines%20the%20object%20you%27re%20looking%20at.)
Implemented the workaround suggested [here](https://github.com/ipython/ipython/issues/11249)

Fix code inspection notebook

---

.github/workflows/pipeline.yaml
pyproject.toml

Tox will install the necessary dependencies per environment, so we don't need to do this beforehand. This should speed up the builds a bit.

Install only test deps before running tox

---

src/fondant/pipeline/pipeline.py
tests/pipeline/test_pipeline.py

Encountered a bug in exception message generation. We were trying to access the `name` field of the `ComponentOp`, which is no longer available. We are now using `component_op.component_name` instead.

Fix exception when invoke consumes with invalid field schema

---

examples/sample_pipeline/pipeline.py
src/fondant/pipeline/compiler.py
tests/pipeline/test_compiler.py
tests/pipeline/test_runner.py
tests/test_cli.py

This bothers me already for some time. Change the mounting of the local base path in the docker compile. Now a local base path is created.

Create local artifact directory if it does not exist

---

.pre-commit-config.yaml
docs/components/hub.md
scripts/component_readme/generate_hub.py
scripts/component_readme/hub_template.md

This PR updates the components path which was changed in #849.

Fix hub generation with new components location

---

scripts/build_components.sh

The build pipeline is currently failing. This should fix it.

Update component dir in build script

---

docs/components/component_spec.md
src/fondant/component/component.py
src/fondant/component/data_io.py
src/fondant/component/executor.py
src/fondant/components/embed_images/src/main.py
src/fondant/components/index_aws_opensearch/src/main.py
src/fondant/components/index_qdrant/src/main.py
src/fondant/components/index_weaviate/src/main.py
tests/component/test_component.py

This PR changes the `dask_client` method introduced in #852 into a general `setup` method.
This method differs from `__init__` in that it allows users to return a state, which is passed into the `teardown` method by Fondant.  This is necessary since the Dask client is not pickleable, and setting it as an instance attribute leads to issues when executing the `transform` method across processes (as is the case in the `PandasTransformComponent`).

Change dask_client to general setup method

---

src/fondant/component/data_io.py

We currently don't preserve the divisions of the data when writing and reading again, which leads to errors when merging datasets with a low and high amount of partitions. This PR enables the writing of a metadata file which should fix this.
This was originally introduced in #391, which contains more information, but then later reverted in #403 without a clear reasoning.
Let's reactivate it, and if there's a reason to remove it again, let's document it properly.

Write metadata file

---

.github/workflows/prep-release.yaml
pyproject.toml
scripts/post-build.sh
scripts/pre-build.sh
tox.ini

The new packaging strategy introduced in #849 doesn't work correctly for wheels due to a bug in poetry (https://github.com/python-poetry/poetry/issues/8994), which breaks installing both from Github and PyPi. This PR introduces a workaround.
Since the bug is related to the `src` directory, this workaround adds a `pre-build/sh` script which unpacks the `src` directory before building, and a `post-build.sh` script which moves the package back into the `src` directory afterwards.
This leads to the following result:
- Installing from Github leads to an installation including all component files
- Installing locally without running the build script leads to an installation including all component files
- Installing from PyPi leads to an installation with only the `fondant_component.yaml` files …

Add pre- and post-build script to work around Poetry bug

---

src/fondant/component/component.py

A component in [my pipeline failed due to an error](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-02-21T09:55:20.056323035Z;endTime=2024-02-21T11:00:14.204778Z;query=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%228518404145068113920%22%0Aseverity%3E%3DDEFAULT%0A--Hide%20similar%20entries%0A-%2528jsonPayload.message%3D~%22%2528%5Cd%7B4%7D-%25280%5B1-9%5D%7C1%5B0-2%5D%2529-%25280%5B1-9%5D%7C%5B12%5D%5B0-9%5D%7C3%5B01%5D%2529%2529%20%2528%2528%5Cd%7B2%7D%2529:%2528%5Cd%7B2%7D%2529%2528%3F::%2528%5Cd%7B2%7D%2528%3F:%5C.%5Cd*%2529%3F%2529%2529%3F%2528%3F:%2528%5B%2B-%5D%2528%3F:%5Cd%7B2%7D%2529:%3F%2528%3F:%5Cd%7B2%7D%2529%3F%7CZ%2529%3F%2529%2529%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%20%5C%7C%20httpx%20%5C%7C%20INFO%5C%5D%20HT …

Catch Dask client shutdown error

---

src/fondant/component/component.py
src/fondant/component/data_io.py

Dask config needs to be set before starting the `LocalCluster`. I first put it into the `DaskDataIO` since it's central to the working of Fondant that this is set correctly, and I didn't want this to be overwritten. That's too late in our flow though. The other place we could put it is in the executor, but we currently try to keep that Dask-agnostic.

Move convert-string into component setup method

---

src/fondant/components/write_to_file/src/main.py

I ran into some issues writing embeddings with this component since the inferred schema was incorrect. Specifying it explicitly solved it.

Specify schema when writing to parquet in write_to_file component

---

src/fondant/component/data_io.py
tests/component/test_data_io.py

We reintroduced writing the metadata file in #864 to preserve the divisions of the data when writing and reading again. We turned this behavior off in the past, but without proper documentation of the reason.
I'm now running into issues with Dask workers dying when writing large datasets though, presumably because of the metadata file, as documented in these Dask issues:
- https://github.com/dask/dask/issues/6600
- https://github.com/dask/dask/issues/3873
- https://github.com/dask/dask/issues/8901
Also, while I ran into issues with the preservation of divisions before, I can't reproduce this locally with a small example. Let's turn writing metadata off again and validate if we are still having issues with this.

Don't write metadata file

---

src/fondant/pipeline/runner.py
tests/pipeline/test_runner.py

The docker version installed on the VM I'm using is `20.10.17` and everything is working if I remove this check. So we can lower it to support a wider range.

Allow more supported docker versions

---

examples/sample_pipeline/pipeline.py
src/fondant/component/data_io.py
src/fondant/component/executor.py
src/fondant/components/load_from_pdf/tests/component_test.py
src/fondant/core/component_spec.py
src/fondant/core/manifest.py
src/fondant/pipeline/pipeline.py
tests/pipeline/test_lightweight_component.py
tests/pipeline/test_pipeline.py

Add test for consume name to name mapping

---

src/fondant/pipeline/compiler.py

PR that adjusts the method of detection of the `base_path`
My local `base_path` named `data_dir` was interpreted as a remote path since it partially matched one of the support fsspec schemes (`data`). Now we strictly detect the protocol from the base path and check if it matches any of the supported fsspec schemes.

Bugfix remote file detection

---

src/fondant/core/schema.py
src/fondant/core/schemas/common.json
tests/component/examples/component_specs/component.yaml
tests/component/test_component.py
tests/core/test_schema.py

Fixes https://github.com/ml6team/fondant/issues/882
openapi spec: https://swagger.io/docs/specification/data-models/data-types/#:~:text=date%2Dtime%20%E2%80%93%20the%20date%2Dtime%20notation%20as%20defined%20by%20RFC%203339%2C%20section%205.6%2C%20for%20example%2C%202017%2D07%2D21T17%3A32%3A28Z

Enable timezone type for timestamp pyarrow type

---

pyproject.toml
src/fondant/component/data_io.py
tests/component/test_data_io.py

This is necessary to prevent OOM when processing large datasets. Added all the info in comments in the code.

Implement non-blocking to_parquet

---

src/fondant/pipeline/compiler.py

Temporarily disabled exposing the Dask diagnostic dashboard  port to the docker setup.
Executing docker containers after each other using docker compose, leads sometimes to the case that the port is already in use.
We should come up with a solution if we want to use the dask dashboard again. 
Fix: #870

Temporarily disabled exposing the Dask diagnostic dashboard 

---

.github/workflows/build.yaml

Merged this accidentally. FYI, the `workflow_dispatch` event means you can already trigger this workflow manually for a PR via the actions page.

Don't run build action on every PR

---

src/fondant/component/data_io.py

`pa.from_numpy_dtype` fails when passing an object dtype, which Dask uses when the dtype is not explicitly known. I propose to fall back on `string` if this is the case. This will probably be correct for the index column in most cases when the `dtype` is unknown, and non-breaking in most other cases.

Add string as fallback index type when writing data

---

src/fondant/components/caption_images/Dockerfile
src/fondant/components/caption_images/src/main.py
src/fondant/components/retrieve_from_faiss_by_prompt/src/main.py
src/fondant/components/segment_images/Dockerfile
src/fondant/components/segment_images/src/main.py

When using the retrieve from faiss component with the LocalCluster it is a bit tricky to find the right machine configuration. 
Changed the initialisation of the LocalCluster. Assign each worker 8Gb of RAM and limit the number of cores accordingly.

Add resource requirements to the retrieve from faiss component

---

src/fondant/component/executor.py
tests/component/test_component.py

n the case that a `PandasTransformComponent` receives an empty dask partition, the execution fails. There could be several reasons why a partition is empty, and it may depend on a custom implementation. We should catch this case and not halt the component's execution.
This PR adds a check to see if the `wrapped_transform` receives an empty partition. If it does, we skip the execution and return the received dataframe.

Skip transformation of partition if partition is empty

---

src/fondant/component/data_io.py
src/fondant/core/manifest.py
src/fondant/dataset/dataset.py
tests/core/examples/evolution_examples/7/component.yaml
tests/core/examples/evolution_examples/7/output_manifest.json
tests/core/test_manifest_evolution.py
tests/pipeline/test_lightweight_component.py

When no produces is defined the location of the dataset couldn't be determined. Leading into list index out of range error. 
Using the dataset index to determine the dataset location.

Empty produces leading into list index out of range

---

README.md

https://fondant.ai/en/latest/guides/first_pipeline returns 404

Fix link in the README file

---

src/fondant/component/data_io.py
src/fondant/dataset/compiler.py
tests/pipeline/test_compiler.py

As part of the new interface and manifest changes this bug appeared. We are not able to run the new fondant version in jupyter notebooks cause the working directory isn't resolved correctly. 
Mounting the complete path instead of the stem solves the issue.

Mount absolute path of working dir to local runner

---

.github/workflows/pipeline.yaml
pyproject.toml

dask <= 2024.4.0 is incompatible with python 3.11.9. Github updated there runners and our cicd pipelines were failing. 
A fix was released as part of dask 2024.4.1, however we can not use this version since there are dependency conflicts with dask-cuda.
<s>Limited our python version to <3.11.9</s>
**Update 16/04/24:** 
We encountered `TypeError "<" not supported between instance of 'int' and 'str'`. This is related to sorting operation part of `dask-expr`. dask-expr is part of `dask>=2024.3.0`. Dask supports a specific configuration to disable the computation graph optimizations and the usage of dask-expr. However, limit the dask version to `dask<2024.3.0` would avoid further issues since we have tested these version before.

Fixing cicd

---

.github/workflows/prep-release.yaml

Our AWS auth GitHub action has role-duration-seconds limit set to 3600 by default. We have to increase this limit as well next to the role configuration itself.

Set session duration to 5h in prep release pipeline

---

scripts/build_base_image.sh

In `0.12.0` the lightweight component that uses a default image are not working. 
- During the build of base images the image tag list wasn't initialised correctly within the loop. This means we have overwritten the previous build images. Every base image now contains python version `10.11.9`
- We have limited dask to`<2024.3.0`, but only dask `>=2024.4.1` is compatible with python `>=10.11.9`. Limit python version of the base image build.

Bugfix:  Fondant base image build
